language: java

jdk:
  - oraclejdk8

services:
  - docker

addons:
  sonarqube: true

after_success:
  - ./gradlew jacocoTestReport coveralls
  - docker build -t sportchef/users .
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push sportchef/users
  - docker logout

env:
  global:
  - secure: I90kwD0lBXsgStjUnJtel03VeW5qldXq4+IBCKQT9HvDPVzTzyrwE+h+KddVO5ngvFRyWW8H8CK+LUXkyGdLvsZ/SwxbtGsk1sidktHua2vvZVFd0wRe3PYbBfhadSpXCEaASIHK56Wvl56F2FiR+mEKuooNzWHapD4GiDBYQnliVndA0CYOno19fDBZK175LYI+dZt4UCb1GNB4OtpGSqhLP5wSY00/j6y18qcczExc0O3EPp68qenWaKq5cDDl5DcgDLbyYfMXTbAfMNCYTwJQ2bJoZT7L86Swq4KVBOF8hrMGeV2V67dOjlBxoxmH3BmRXkoWLlbLaQSO+000qOWJAJ19/hmLoLzPen+KCk8sxpSUPkOYZ5fKz5huY4ZHMcojAVzgqZl2YJpq4TRQ13pBDIGdGkeav9G2TWwSdwrBX3VDsNOO02kZuJo++4qqcE/Lr/LiGPdmX9DGLX52WqKHd0uDtzwbqsrpblW+RprWXSyiOYwzpHfmlO0ocDzskUsBKhgvJ4/tZ2pP6MEWY3X2+CneWkp7Ck6Tj/8qhB9KtaqJEmEmAxNWk+GfZ0Cz1dM1G/u3F1C1LUg5wVZ//YwhNI3Y/RCwCYXE12gEod251fXjuHG4lLrRw/+0B3300ni5O8GTVids2xds2jyCyKKBYgcDEanmQDtRt9oLPUU=
  - secure: l/pQ8DJyNY6i4xSSve+qHh8MdCE3LEvtCi6CXb5pbSW3zZySVS5O1Kv3WlT/Q2c2hMRpiEsH6mluG21P1QiC8h9jRq9X2pc/7D58kzDcUawh2EtTdtwzUdnHRORaapGZZe8uzyC+d6N4Cu7OE2v7hDRkRHu7jd0ZWMBssupV1tQRYJhf7VQw8hWUHfBVAyrV2rvS4l0IKHzQuFCDbBmewHzSyUmw0vvkvTiBF4Lr2JfIuMpKsR1CrxkGpq3Myn+/ENT+r9g+3l1nVy+DxD6KE2rDqAlQLPwkeRsBqdGPxwxK0kNqTUlpjC4Rhvd+T+3bLEXPDj3YjLPqTLBA/OBTqxu4efAMZtO8Kj9GY2liU3790a2MGDvf8EI0kXsOPpjcU3muK2jmRErvfkTdY14ugZv/b/icmnM0kReh157L7AfUqzGk65xZT6avbaHwU7d9mpiX1R5Vf8VUKza9wxhnCjD6eU7Y3p+ikxQmKho+jFEy119/eOxRuOphxzCLVro754XOimd/1TpiDybl+hTM1Dj0hi2lBzpKQP/h0pyUWgDChmU5R3UkRxScnYmvEDQafrLRCpnBGzKJGahuzMMd7WM4Z05fqyU/GQ+vzFS0EBsfc8Dc38RWJGPOradNMQNdTBvIEjk7DXswYIE895Bn6lcTlUO1VzuFYf3zKimViEw=
  - secure: n5HN+tLYtrsRXqDghchSKMLXdJrJjugoE/r2Pt4RS96/R27YlczboQWtfW/7sPPwAl5VJRnpXDbjtHgfDXXCL4Lx6R6mwGRszvmnzgAgsM05BeW3XM3gWSurVaFt4WQqkIu2UM6lbo8GGAub/MGW7cyZayg+LeH8/c4D/ZufPXuIHXk890PCqCIF5fUt6It+zTt+VM00Ru57barIzdmRq6XUDqRtdt8JufTL8dFjQoCbg/o0rhEORkrnkI0ti5/LeUskS0Dqc9/ShcZRkWInl5WMXsZI1gQOmgmW3bAvzJ5tU0nIb8ANYF8rpBjLdKd1wS1EJsK5Ob5QwuTU0x/2E46ywUuIgQeqJWKjXI4rZtQivowg6Z4tZqsaRmI26NYmqerc32UCvzSysKbpStkeg1W1survYJ2Eo1/l9uLbwB/x9l1u0lgJw0Co3qlQ50SHIG3nEi51ACgyUkvZmQ0lFlaOvpJSn2c46l4NbigZBfvRf0F38iJqiPkrL9KkBNqikbR7OhNNtjKGlzW5T2G7ga4Yvu086lj9jjuXvMxAtyplyQK0jSZOCUf0m/cVgWF+JzyeEJ33TxzI8WEmtuE8JVsenT5JPM/1DicQPNeY5DVWgCDwLqMForY82gGzplD6TCVciiGYtNs0ZLCRaovCmtqkBxiBXQ+FwJag6/iWo4M=

script:
  - ./gradlew check
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN
